version: '3.5'

services:
  nginx:
    image: nginx
    container_name: lear-php-nginx
    ports:
      - '8080:80'
    volumes:
      - './.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
      - './:/code'

  web:
     build:
          dockerfile: ./Dockerfile
     container_name: learn-php-web
     tty: true
     volumes:
         - './:/code'

  mysql:
    image: mysql:8
    container_name: learn-php-mysql
    environment:
      MYSQL_DATABASE: alculator_histories_database
      MYSQL_USERNAME: vasilich
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - "3306:3306"